# ############# BIND MOUNTING COMPILLED CLASSES ####################################################

FROM eclipse-temurin:26-jre

WORKDIR /app

ENTRYPOINT ["java", "-cp", "/app/BOOT-INF/classes:/app/BOOT-INF/lib/*", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dspring.profiles.active=dev", "com.swetlokognatsk.authorization_server.AuthorizationServerApplication"]

# TODO figure out how to use these other ways
# # ############# MULTISTAGE_BUILD_V2 ####################################################
# FROM eclipse-temurin:26-jre AS builder

# WORKDIR /builder

# ARG JAR_FILE=target/*.jar
# COPY ${JAR_FILE} app.jar

# RUN java -Djarmode=tools -jar app.jar extract --layers --destination extracted

# FROM eclipse-temurin:26-jre

# WORKDIR /app

# COPY --from=builder /builder/extracted/dependencies/ ./
# COPY --from=builder /builder/extracted/spring-boot-loader/ ./
# COPY --from=builder /builder/extracted/snapshot-dependencies/ ./
# COPY --from=builder /builder/extracted/application/ ./

# # ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]
# # ENTRYPOINT ["java", "-Dspring.devtools.restart.enabled=true", "-Dloader.path=/app/BOOT-INF/classes", "-jar", "app.jar"]
# ENTRYPOINT ["java", "-Dloader.path=/app/BOOT-INF/classes", "-jar", "app.jar"]

# ############# MULTISTAGE_BUILD_V1 ####################################################
# FROM maven:3.9-eclipse-temurin-26 AS external_and_standard_libs

# WORKDIR /app

# COPY pom.xml .
# RUN mvn dependency:go-offline

# COPY src src
# RUN mvn -B package -DskipTests

# FROM eclipse-temurin:26

# WORKDIR /app

# COPY --from=external_and_standard_libs /app/target/*.jar app.jar

# # NOT FOUND BY SOME REASON!
# # TODO whatis -Djava.security.egd=file:/dev/./urandom
# ENTRYPOINT ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dspring.profiles.active=dev", "-Dloader.path=/app/BOOT-INF/classes", "-Djava.security.egd=file:/dev/./urandom", "org.springframework.boot.loader.launch.JarLauncher"]


# ########### SECOND OPTION
# FROM maven:3.9.16

# WORKDIR /app

# COPY . .

# CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev", \
#      "-Dspring.devtools.restart.enabled=true", \
#      "-Dspring.devtools.livereload.enabled=true", \
#      "-Dspring.devtools.remote.secret=mysecret"]


########## FIRST OPTION
# FROM maven:3.9.6-eclipse-temurin-17 AS dev
# WORKDIR /app

# # Copy configuration metadata first to leverage cache layers
# COPY pom.xml .
# RUN mvn dependency:go-offline

# # Copy the actual source directory
# COPY src ./src

# # Expose app port and DevTools remote traffic port (if needed)
# EXPOSE 8080

# # Run Spring Boot via plugin to allow live reloading
# CMD ["mvn", "spring-boot:run"]