services:
  authorization-server:
    container_name:
      'authorization-server'
    build:
      context: '../authorization_server'
      dockerfile: './.docker/Dockerfile.dev'
    volumes:
      - '../authorization_server/target/classes:/app/BOOT-INF/classes:delegated'
      - '../authorization_server/target/lib:/app/BOOT-INF/lib:delegated'
    env_file:
      '../authorization_server/.docker/.env'
    ports:
      - "${AUTHORIZATION_SERVER_PORT}:8081"
      - "5015:5005"
    depends_on:
      - postgres

  client:
    container_name:
      'client'
    build:
      context: '../client'
      dockerfile: './.docker/Dockerfile.dev'
    volumes:
      - '../client/target/classes:/app/BOOT-INF/classes:delegated'
      - '../client/target/lib:/app/BOOT-INF/lib:delegated'
    env_file:
      '../client/.docker/.env'
    ports:
      - "${CLIENT_PORT}:8082"
      - "5016:5006"

  protected-resource:
    container_name:
      'protected-resource'
    build:
      context: '../protected_resource'
      dockerfile: './.docker/Dockerfile.dev'
    volumes:
      - '../protected_resource/target/classes:/app/BOOT-INF/classes:delegated'
      - '../protected_resource/target/lib:/app/BOOT-INF/lib:delegated'
    env_file:
      '../protected_resource/.docker/.env'
    ports:
      - "${PROTECTED_RESOURCE_PORT}:8083"
      - "5017:5007"
    depends_on:
      - postgres

  postgres:
    image: 'postgres:18.6'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    volumes:
      - pg_db:/var/lib/postgresql

  redis:
    container_name:
      'oauth_redis'
    image: 'redis:8.8.2'
    restart: no
    volumes:
      - './redis/redis.conf:/usr/local/etc/redis/redis.conf'
      - 'redis_data:/data'
    ports:
      - "6379:6379"
    command: >
      redis-server
      /usr/local/etc/redis/redis.conf


volumes:
  pg_db:
  redis_data: