spring.application.name=authorization_server
server.port=8081

spring.docker.compose.file=./.docker/compose.dev.yaml
spring.docker.compose.stop.command=down
# TODO what does it do
spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://postgres:5432/oauth_2_0_learning
spring.datasource.username=root
spring.datasource.password=password

spring.data.redis.host="redis"
spring.data.redis.port=6379
# spring.data.redis.username=root
spring.data.redis.password=password
