spring.application.name=authorization_server
server.port=8081

spring.docker.compose.file=./.docker/compose.dev.yaml
spring.docker.compose.stop.command=down
# TODO what does it do
spring.devtools.restart.enabled=true