server.port=8081

spring.docker.compose.file=./.docker/compose.dev.yaml
spring.docker.compose.stop.command=down

spring.devtools.restart.quiet-period=1500ms
spring.devtools.restart.poll-interval=2000ms