spring.application.name=protected_resource
server.port=8083

spring.docker.compose.file=./.docker/compose.dev.yaml
spring.docker.compose.stop.command=down

spring.datasource.url=jdbc:postgresql://postgres:5432/oauth_2_0_learning
spring.datasource.username=root
spring.datasource.password=password

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml